//import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "../globals.css";

const notoSans = Noto_Sans_KR({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <div>Авторизация</div>
        {children}
      </body>
    </html>
  );
}
